#MSYS Launcher configure
[Launcher]
# MSYSTEM hava 3 type MSYS MINGW32 MINGW64
MSYSTEM="MINGW64"
Root="D:/MPOSIX2"
WD="D:/MPOSIX2/usr/bin"
Mintty="D:/MPOSIX2/usr/bin/mintty.exe"
EnableZshell=false
Shell="bash"
UseClearEnv=true
ICONPath="/msys2.ico"
#AppendShellArgs="Hello world"
#AppendPath=[
#  "D:/Tools/Path"
#]

